COPY cloud4.lfacebook    ( url) TO '/home/spider/raw/cloud4.lfacebook.csv' WITH DELIMITER='\t' AND HEADER=true;
COPY cloud4.llinkedin    ( url) TO '/home/spider/raw/cloud4.llinkedin.csv' WITH DELIMITER='\t' AND HEADER=true;
COPY cloud4.ltwitter     ( url) TO '/home/spider/raw/cloud4.ltwitter.csv' WITH DELIMITER='\t' AND HEADER=true;
COPY cloud4.lyoutube     ( url) TO '/home/spider/raw/cloud4.lyoutube.csv' WITH DELIMITER='\t' AND HEADER=true;
COPY cloud4.lwordpress   ( url) TO '/home/spider/raw/cloud4.lwordpress.csv' WITH DELIMITER='\t' AND HEADER=true;
COPY cloud4.linstagram   ( url) TO '/home/spider/raw/cloud4.linstagram.csv' WITH DELIMITER='\t' AND HEADER=true;
COPY cloud4.lflickr      ( url) TO '/home/spider/raw/cloud4.lflickr.csv' WITH DELIMITER='\t' AND HEADER=true;
